name = "SincBridgeDynamics"
uuid = "00cd6036-d45e-44b0-92d3-4a2eaae29a41"
authors = ["Antonio Romero Ordóñez"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
